
object Versions {
    internal const val ktxVersion = "1.7.0"
    internal const val appCompactVersion = "1.4.1"
    internal const val materialVersion = "1.5.0"
    internal const val constraintLayoutVersion = "2.1.3"
    internal const val junitVersion = "4.+"
    internal const val junitExtVersion = "1.1.3"
    internal const val espressoVersion = "3.4.0"
    internal const val navVersion = "2.4.1"
    internal const val hiltVersion = "2.38.1"
    internal const val retrofitVersion = "2.9.0"
    internal const val gsonVersion = "2.9.0"
    internal const val coroutinesVersion = "1.6.0"
    internal const val viewModelVersion = "2.2.0"
    internal const val activityKtxVersion = "1.4.0"
    internal const val roomVersion = "2.4.2"
    internal const val workVersion = "2.7.1"
}
object Dependencies {
    const val ktx = "androidx.core:core-ktx:${Versions.ktxVersion}"
    const val appCompact = "androidx.appcompat:appcompat:${Versions.appCompactVersion}"
    const val material = "com.google.android.material:material:${Versions.materialVersion}"
    const val constraintlayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayoutVersion}"
    const val jUnit = "junit:junit:${Versions.junitVersion}"
    const val jUnitExt = "androidx.test.ext:junit:${Versions.junitExtVersion}"
    const val espresso = "androidx.test.espresso:espresso-core:${Versions.espressoVersion}"
    const val navigationFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.navVersion}"
    const val navigationUi = "androidx.navigation:navigation-ui-ktx:${Versions.navVersion}"
    const val hilt = "com.google.dagger:hilt-android:${Versions.hiltVersion}"
    const val hiltCompiler = "com.google.dagger:hilt-android-compiler:${Versions.hiltVersion}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofitVersion}"
    const val gsonConverter = "com.squareup.retrofit2:converter-gson:${Versions.gsonVersion}"
    const val coroutine = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutinesVersion}"
    const val viewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.viewModelVersion}"
    const val activityKtx = "androidx.activity:activity-ktx:${Versions.activityKtxVersion}"
    const val room = "androidx.room:room-runtime:${Versions.roomVersion}"
    const val roomCompiler = "androidx.room:room-compiler:${Versions.roomVersion}"
    const val roomKtx = "androidx.room:room-ktx:${Versions.roomVersion}"
    const val work  = "androidx.work:work-runtime-ktx:${Versions.workVersion}"
}